### ISSUE TITLE
VCR usage

### ISSUE THREAD

**Issue by rurounijones** [tokyorails/tokyorails#13]
From what I can see at the moment we are not 100% mocking out calls to the meetup API. This is because we have added the vcr_cassettes directory to .gitignore. 

I am pretty sure this is not how it should be done. VCR responses should be saved for all future test runs so that we have deterministic responses to our mocked calls, at the moment the first call is not mocked in a new dev environment for example. 

With the current setup all the event specs in my environment were failing because they were expecting at least one upcoming event (Which was the case for the developer when the tests were written) but we currently have no upcoming events.

I think we need to get rid of the .gitignore entry and commit the vcr_cassettes along with everything else.

**Comment by tapster** [comment]
What we found on another project is that the vcr cassettes often add a lot of noise to commits so diffs and merges become annoying. Especially with all the image binary data in there.

I think what you found by regenerating in a new environment is actually great - we need to add coverage for when there are no upcoming events - since the page now is blank on the site :)

**Comment by rurounijones** [comment]
But if we cannot mock out the meetup calls totally how can we test all scenarios? For example in the aforementioned events we would want to test what happens when there IS an upcoming event and their ISN'T an upcoming event. How can we do that without mocking out the HTTP call and returning specific responses?

In fact, the more I look at VCR I do not see what major advantages it has over plain old webmock + a helper method to locate the correct file to load into a stubbed out response body.

The only advantage I can see is the fact that it automatically creates the responses but we are not using that advantage because we are not saving the cassettes (and now I have looked at those yml files...gawd are they ugly and unreadable).

I will create a branch using the same simple webmock method I used in past projects as a comparison.

**Comment by tapster** [comment]
ah, just to clarify, the cassettes are in fact saved locally - just not checked in to avoid the ongoing commit noise - so they're generated on the first run and then used each subsequent spec run

You are correct, we need to mock out the responses and cover error cases. I started without vcr and just webmock but interested to hear any strong for and against. Seems very useful in some cases, less so in others

**Comment by rurounijones** [comment]
Here is a commit on how I would test the event_specs without using VCR rurounijones/tokyorails@66a7d85475ff56a3ac998397a4171bfd19dfc988

From what I can see the main advantages of VCR is:
- automatic recording of responses. This advantage is currently nullified because we are not currently committing them. 
- It records EVERYTHING about the response including headers etc.
- has a handy method which means you do not need to stub out requests manually.

The disadvantages are:
- the response.yml files are not human readable (binary body) while the webmock stubs in my commit are.
- Ugly as hell response files saved to repository (The main reason they were not being committed in the first place)

Personally I think that if we are not saving the VCR responses then we might as well dump VCR and just use the method as shown in the above commit. If we DO save VCR responses then I am a bit more torn, I like all the automagical stuff around it but hate that the responses are not human readable

**Comment by tapster** [comment]
I think at this stage your proposal makes more sense, so +1 from me

I actually used that style originally eg. https://github.com/tokyorails/tokyorails/commit/c3bd5840b514ee30bfb1b687874b3cb65bed28f3 but definitely interested to hear other opinions.

for me, vcr has value in some cases, but where we have just a few calls to stub out, Im not so sure of the value.

one thing to clarify though, not saving the yml files in the repo is to avoid the noise, but doesn't nullify the benefits. After the first run, you have the response yml locally, then all subsequent spec runs use the saved responses as usual. it just keeps them out of the repo. we do this on a current project that parses remote content from many sources, so makes a big difference since we're running the specs continuously

**Comment by adamakhtar** [comment]
Im fine with either. The big advantage of VCR is that not only does it record the response but it can be set to rerecord at a user set interval which guards your tests from any changes to the meetup api. For this project though that isnt mission critical. 

regards to checking in or ignoring cassettes in git  - this must be a common question for many teams using vcr. Ill do a quick search but feel free to just make the switch.

**Comment by rurounijones** [comment]
The thing I think I must be missing is:

In my commit I can return various responses for various test scenarios. (An event is upcoming, an event is not upcoming). From what I can see this cannot be done with VCR.

How can you test all the possibilities without controlling the responses yourself unless you happened to have the correct response you needed from the live API for the test at the time you wrote it (Which is not guaranteed for others because it is not committed in the repository which is why the VCR'd event specs were failing for me but presumably working for the dev who wrote them.)

**Comment by adamakhtar** [comment]
No your right. We can only record what the current state of the tokyo rails is on meetups.com. So if we want to test other states such as 0 events then we would have to fake that manually. So why bother use vcr at all? 

Well for this small project probably no major advantage. But if it were a bigger project then the idea of having your stubbed responses autoupdate is nice, plus any states you need to explicitly fake you can do manually. Im sure mixing your own stubs with vcr is no problem. 

I think the events which are being vcr'd are too unpredictable. One month 0 upcoming events, the next month there are 3 queued up. If we were testing responses for a youtube search for michael jackson im sure vcr would be great because we could be pretty damn sure that there will always be results returned. 

Because of this, for the tests in question, I set vcr to record only once. But I didnt know cassettes were not being versioned. Hence when you ran them, vcr found no cassette and had no choice but to query the api again  by which point the number of events had probably increased by at least one. 

So the options are

1 ) Commit tapes 
or
2) Go old school and do it manually.

i think 2 looks the better way considering the small scale of this project and unpredictable live data.

**Comment by rurounijones** [comment]
Phew, thanks for the clarifications, I wasn't sure if I was being extremely thick and missing something obvious.

I won't have time to do anything until this weekend but unless someone objects then my plan will be to put a pull request on the above commit (After a bit of clean-up), write tests for the import script and then write some Github integration stuff so we can easily pull user's repos etc. All of that will be done using old-skool webmock stubbing.

**Comment by phuongnd08** [comment]
I stumped upon this discussion by searching around google and I find it interesting. In my experience, committing the cassettes is a good thing. Merging it should not be an issue (as with picture) since you just need to override it with whatever the later version is. In the worst case, you can just delete the cassettes and re-run the test, right? Sure it may not be readable but why would you read it? With review tools like GitX or SourceTree, you can easily ignore it while reviewing. The committing them to repo has number of benefits: The test is guaranteed to be independent. Imagine at a certain time, when the test run, the remote server suddenly down (or some connection problem) then the tests would fail but it's not indicating an issue with the code but rather the unstable condition the tests are being run. Other case would be in the CI server. The CI server doesnot keep the previous test result. It should help the CI server gains some speed by not re-requesting these request over and over.
